- name: Create all directories
  file: path=/app/portainer/data state=directory mode=0755

- name: Copy docker-compose file
  copy:
    src: docker-compose.yaml
    dest: /app/portainer/docker-compose.yaml
    mode: 0600

- name: Deploy portainer stack
  shell: 'docker stack deploy -c /app/portainer/docker-compose.yaml portainer'