- name: Create all directories
  file:
    path: "{{ portainer_volume }}/data"
    state: directory
    mode: 0755

- name: Copy docker-compose file
  template:
    src: docker-compose.yaml
    dest: "{{ portainer_volume }}/docker-compose.yaml"
    mode: 0600

- name: Deploy portainer stack
  shell: "docker stack deploy -c {{ portainer_volume }}/docker-compose.yaml portainer"