version: '3.6'
services:
  ui:
    image: portainer/portainer
    command: --host=unix:///var/run/docker.sock #--templates http://templates/templates.json
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/portainer/data:/data
    deploy:
      labels:
        traefik.port: 9000
        traefik.backend: portainer
        traefik.frontend.rule: PathPrefixStrip:/portainer/
        traefik.docker.network: traefik_net
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

#  templates:
#    image: portainer/templates
##    volumes:
##      - ./templates:/usr/share/nginx/html
#    ports:
#      - 9999:80
#    networks:
#      - portainer
#    deploy:
#      replicas: 1
#      placement:
#        constraints: [node.role == manager]
#      restart_policy:
#        condition: any
#        delay: 5s
#        max_attempts: 3
#        window: 120s

networks:
  traefik:
    external: true
    name: traefik_net