version: '3.6'

services:
  traefik:
    image: traefik
    command:
      - --docker
      - --docker.swarmMode
      - --docker.domain=traefik
      - --docker.watch
      - --api
    networks:
      - net
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 3s
        max_attempts: 5
        window: 60s

networks:
  net: